name: New Script
description: Template for post scripts
title: "<insert script name as title>"
assignees:
  - ManuD33P,DanteSandDev,bsjaramillo
body:
  - type: input
    id: script-author
    attributes:
      label: Script author
      description: Your nick name, name or author of this script
    validations:
      required: true
  - type: input
    id: script-name
    attributes:
      label: Script name
      description: Input your script name
      placeholder: awesomescript.js
    validations:
      required: true
  - type: textarea
    id: script-description
    attributes:
      label: Script description
      description: A short description about your script.
      placeholder: An awesome script for awesome things !
    validations:
      required: true
